---
kind: pipeline
type: ssh
name: master

server:
  host: 
    from_secret: DEV_HOST
  user: ubuntu
  ssh_key:
    from_secret: DEV_SSH_KEY

steps:
- name: master_deploy
  commands:
  - echo "HELLO THIS IS PATRICK"
  - cd /tmp
  - rm -rf /tmp/stratus-motd
  - git clone git@github.com:magemojo/stratus-motd.git /tmp/stratus-motd
  - cd /tmp/stratus-motd/
  - rsync -avz /tmp/stratus-motd/ /home/ubuntu/web/magemojo/motd/ --exclude=.git*
  
trigger:
  branch:
  - master
  event:
  - push
  - merge
clone:
  disable: true
---
kind: pipeline
type: ssh
name: dev

server:
  host: DEV_HOST
  user: ubuntu
  ssh_key:
    from_secret: DEV_SSH_KEY

steps:
- name: dev_deploy
  commands:
  - echo "HELLO THIS IS PATRICK"
  - cd /tmp
  - rm -rf /tmp/stratus-motd
  - git clone git@github.com:magemojo/stratus-motd.git /tmp/stratus-motd
  - cd /tmp/stratus-motd/
  - rsync -avz /tmp/stratus-motd/ /home/ubuntu/web/magemojo/motd/ --exclude=.git*
  
trigger:
  branch:
  - dev
  event:
  - push
  - merge
clone:
  disable: true
---
kind: pipeline
type: kubernetes
name: slack

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: SLACK_HOOK
    channel: magemojo-github
    template: >
      {{#success build.status}}
        {{repo.name}} build {{build.number}} on branch {{build.branch}}, commit by {{build.author}}. Good job.
      {{else}}
      {{repo.name}} build {{build.number}} on branch {{build.branch}}, commit by {{build.author}} failed. Fix me please.
      {{/success}}

depends_on:
  - dev
  - master